Add files
ahmedtaa/Hello-Microverse pull request #2
Opened 2021-11-23 14:35 UTC by ahmedtaa

**In this project I did:**

### Add 3 files (each one in a separate commit):

- A .html file that includes a header with the text "Hello Microverse!". Use the h1 tag for that.
- A .css file that includes one class with styles for your header (make it in your favorite color).
- A test.MD file with the text "This file should be ignored by git".

2021-11-23 15:02 UTC, alonsofl requested changes
Hi @ahmedtaa,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] You have done a good job with your PR description but I would suggest updating the PR title to give more information about the changes introduced in the PR (e.g., Setup project, Add index with a stylesheet and linters). Remember that in a remote workflow we have to deal with timezones and giving the most information possible could help us with delays when asking for more information :pushpin: :wink:

_Check the comments under the review._

## To highlight :dart:
- Commit messages are meaningful :heavy_check_mark:
- Well documented PR description :heavy_check_mark:
- Well documented README :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 15:02 UTC, alonsofalconi commented on .gitignore
> +test.md
- [ ] You have done an excellent job with your project but I would suggest also ignoring the `node_modules` folder for better practices because sometimes by mistake it could be uploaded and it is not necessary (also, it is a really huge folder :sweat_smile:). You could find how to ignore the `node_modules` folder [here](https://www.freecodecamp.org/news/gitignore-what-is-it-and-how-to-add-to-repo/) :wink:

2021-11-23 15:02 UTC, alonsofalconi commented on index.html
> +    <h1>Hello Microverse!</h1>
- [ ] There is an issue when applying the styles because the `<h1>` it's showing with the default color. I think the issue is because you are missing the `<link rel="stylesheet" href="<YOUR_STYLESHEET_PATH_HERE>">` tag in the `<head>` section :pushpin: :smiley:
![image](https://user-images.githubusercontent.com/81522435/143047280-fd5dac7a-a0cb-4367-80c5-176304bffd6d.png)
![image](https://user-images.githubusercontent.com/81522435/143047324-441081fb-6c57-4fcf-b4e9-51b04dcb6fdf.png)

2021-11-23 15:02 UTC, alonsofalconi commented on style.css
> +/* stylelint-disable-next-line rule */
- [ ] I strongly suggest not disabling linters for any reason because these will help us with better practices. I think the Stylelint error that you're getting is because you have to add an empty line at the end of the file. You can see these issues running `npx stylelint "**/*.{css,scss}"` locally :wink:
![image](https://user-images.githubusercontent.com/81522435/143047971-c0d2a9db-a5a2-43ad-95ce-fae592832dc7.png)

2021-11-24 07:49 UTC, ahmedtaa commented on .gitignore
> +test.md
Done

2021-11-24 07:50 UTC, ahmedtaa commented on index.html
> +    <h1>Hello Microverse!</h1>
done

2021-11-24 07:50 UTC, ahmedtaa commented on style.css
> +/* stylelint-disable-next-line rule */
done

2021-11-24 08:11 UTC, Cathella approved these changes
### Hi @ahmedtaa 👋🏻, 

## 🟢 STATUS: APPROVED

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-24 08:11 UTC, Cathella commented on index.html
> +    <link rel="stylesheet" href=style.css>
- [ ] [Optional] I am suggesting adding qoutes to the `href` attribute. You can refer to this reference for the [how to create a link](https://www.w3schools.com/html/html_links.asp)

2021-11-24 13:41 UTC, merged